### PR TITLE
KDE KF6 update

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by travier** [comment]
```
{
    "errors": [
        "appstream-missing-screenshots"
    ],
    "warnings": [
        "appstream-screenshot-missing-caption"
    ],
    "appstream": [
        "E: org.kde.kruler.desktop:~: desktop-app-launchable-omitted"
    ],
    "message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
}
```

**Comment by Justinzobel** [comment]
https://invent.kde.org/graphics/kruler/-/merge_requests/29

**Comment by bbhtt** [comment]
I've added an exception to this. Appstream does not generate screenshot thumbnails for certain image dimensions (too short height/width).

The scrrenshot here is 696x37 px.

**Comment by bbhtt** [comment]
bot, build

**Pull request merged**
